services:
  node1:
    image: nixos/nix:master
    volumes:
      - ".:/app:ro"
      - "nix:/nix"
      - "go:/root/go"
      - "./nix.conf:/etc/nix/nix.conf:ro"
    working_dir: "/app"
    command: nix develop --impure -c go run ./node
    environment:
      - NIXPKGS_ALLOW_UNFREE=1
    networks:
      - default

  node2:
    image: nixos/nix:master
    volumes:
      - ".:/app:ro"
      - "nix:/nix"
      - "./nix.conf:/etc/nix/nix.conf:ro"
      - "go:/root/go"
    working_dir: "/app"
    command: nix develop -c go run ./node
    networks:
      - default

  node3:
    image: nixos/nix:master
    volumes:
      - ".:/app:ro"
      - "nix:/nix"
      - "./nix.conf:/etc/nix/nix.conf:ro"
      - "go:/root/go"
    working_dir: "/app"
    command: nix develop -c go run ./node
    networks:
      - default

  node4:
    profiles:
      - optional
    image: nixos/nix:master
    volumes:
      - ".:/app:ro"
      - "nix:/nix"
      - "./nix.conf:/etc/nix/nix.conf:ro"
      - "go:/root/go"
    working_dir: "/app"
    command: nix develop -c go run ./node
    networks:
      - default

  client:
    image: nixos/nix:master
    volumes:
      - ".:/app:ro"
      - "./log:/log"
      - "nix:/nix"
      - "./nix.conf:/etc/nix/nix.conf:ro"
      - "go:/root/go"
    working_dir: "/app"
    command: nix develop -c go run ./client
    networks:
      - default
    depends_on:
      - cloud

  cloud:
    image: nixos/nix:master
    volumes:
      - ".:/app:ro"
      - "nix:/nix"
      - "./nix.conf:/etc/nix/nix.conf:ro"
      - "go:/root/go"
    working_dir: "/app"
    command: nix develop -c sh -c  'tc qdisc add dev eth0 root netem delay 17ms && go run ./cloud'
    networks:
      - default
    cap_add:
      - NET_ADMIN

networks:
  default:

volumes:
  nix:

  go:
