services:
  node1:
    image: nixos/nix:master
    volumes:
      - ".:/app:ro"
      - "nix:/nix"
      - "go:/root/go"
      - "./nix.conf:/etc/nix/nix.conf:ro"
    working_dir: "/app"
    command: nix develop -c go run ./node
    networks:
      - default

  node2:
    image: nixos/nix:master
    volumes:
      - ".:/app:ro"
      - "nix:/nix"
      - "./nix.conf:/etc/nix/nix.conf:ro"
      - "go:/root/go"
    working_dir: "/app"
    command: nix develop -c go run ./node
    networks:
      - default

  node3:
    image: nixos/nix:master
    volumes:
      - ".:/app:ro"
      - "nix:/nix"
      - "./nix.conf:/etc/nix/nix.conf:ro"
      - "go:/root/go"
    working_dir: "/app"
    command: nix develop -c go run ./node
    networks:
      - default

networks:
  default:

volumes:
  nix:

  go:
